repository: fernando2393/fernando2393.github.io


layout: sidebar
style: dark
show_hire: "false" # To Display the Available for hire or not, even if you are not in a company
show_projects: "true"
show_tech: "true"
show_organizations: "true"
show_topics: "true"
is_organization: "false"  # To display the bio or the description


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 7
  exclude:
    archived: false
    forks: false
    projects:
      - fernando2393.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: fernando-garcia-sanz
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  Deep Learning: "true"
  Machine Learning: "true"
  Python: "true"

organizations:
  Fernando: "false"
  KTH: "true"
  UC3M: "true"
  UTS: "true"
  FORKS: "false"

technologies:
  # Bitcoin: "true"
  Python: "true"
  Java: "true"
  C: "true"
  Tensorflow: "true"
  # JavaScript: "true"
  Keras: "true"
  Jupyter Notebook: "true"
  # Monero: "true"
  # React: "true"
  # Rust: "true"
  # SQL: "true"
